---
title: "CSE160-FinalProject"
author: "Kevin Cawood"
date: "2024-05-04"
output: html_document
---

Read the .csv in

```{r}
missions_df <- read.csv(file = "./Wildland_Search_and_Rescue_Missions_by_NYS_Forest_Rangers__Beginning_2012.csv", header=TRUE)
#clean the data by removing empty values
missions_df <- na.omit(missions_df)
print(missions_df)
```

using the df, create the rows needed for each rescue method

```{r}

fix_str <- function(x) {
  return (gsub("/",".OR.",gsub(" ",".",toupper(x))));
}

#get all unique rescue types
tmp_types <- unique(missions_df$TECHNIQUE)
tmp_types <- strsplit(tmp_types, split = "; ")
tmp_types <- na.omit(tmp_types)
rescue_types <- c()

for(i in 1:length(tmp_types)) {
  for(j in 1:length(tmp_types[[i]])) {
    rescue_types <- append(rescue_types, tmp_types[[i]][j])
  }
}


rescue_types <- na.omit(rescue_types)
rescue_types <- unique(rescue_types)
rescue_types <- fix_str(rescue_types)


#create new columns in missions_df
for(i in 1:length(rescue_types)) {
  missions_df[,rescue_types[i]] <- 0L
}

#going through all fields, assign T/F to new col based on $TECHNIQUE
for(i in 1:length(missions_df$TECHNIQUE)) {
  types <- strsplit(missions_df$TECHNIQUE[i], split = "; ")
  for(j in 1:length(types)) {
    missions_df[i,fix_str(types[[j]])] <- 1L
  }
}

#remove old col
#missions_df$TECHNIQUE <- NULL

activites <- unique(missions_df$ACTIVITY)
situations <- unique(missions_df$SITUATION)

list_for_median <- c()

for (type in rescue_types) {
  filter <- eval(parse(text = paste("missions_df$",type," == 1",sep="")))
  print(paste(type,": ",nrow(missions_df[filter,])))
  print(paste("Activities:",length(activities),"Activities in subset:",length(unique(missions_df[filter,]$ACTIVITY))))
  print(paste("Situations:",length(situations),"Situations in subset:",length(unique(missions_df[filter,]$SITUATION))))
  
  list_for_median <- c(list_for_median,nrow(missions_df[filter,]))
  
}
missions_df

train_size <- (5/6) * nrow(missions_df)
test_size <- nrow(missions_df) - train_size
fold_size <- train_size/5

print(paste("TRAIN SIZE:",train_size,"TEST SIZE:",test_size,"FOLD SIZE:",fold_size))

median_size <- as.integer(mean(list_for_median))
fold_size <- median_size
print(paste("Median size",median_size))

train_df <- missions_df[sample(nrow(missions_df),train_size,replace=FALSE),]
test_df <- missions_df[sample(nrow(missions_df),test_size,replace=FALSE),]
```

```{r}
library(e1071)
library(dplyr)

#factorization
missions_df$INCIDENT.REGION <- as.factor(missions_df$INCIDENT.REGION)
missions_df$ACTIVITY <- as.factor(missions_df$ACTIVITY)
missions_df$SITUATION <- as.factor(missions_df$SITUATION)
missions_df$SUBJECT.GENDER <- as.factor(missions_df$SUBJECT.GENDER)

#missions_df$Carry_out_by_foot <- as.factor(missions_df$Carry_out_by_foot)

#missions_df

#YOUR CODE GOES HERE

#rescue_types

get_acc <- function(df,form,type) {
  
  result <- tryCatch({
    model <- glm(formula = form,data=df,family=binomial)
    
    svm_pred_results <- predict(model,newdata = test_df)
    
    svm_pred_results_thresh <- ifelse(svm_pred_results > .5,1,0)                                      
    svm_tab <- table(test_df[,type],svm_pred_results_thresh)
    print(svm_tab)
    
    accuracy <- format(sum(diag(svm_tab))/sum(svm_tab) * 100, digits = 3)
    return(accuracy)
}, error = function(e) {
  return(NA)
})
  
}

for(type in rescue_types) {
  
  if (type == "EVACUATION.BY.ANIMAL") {
    next
  }
  
  colname <- paste("train_df$",type)

  #combined_df <- missions_df[0,]
  
  #print(paste("SIZE OF COMBINED DF HERE:",nrow(combined_df)))
  
  train_on_situation <- FALSE
  
    
  true_condition <- eval(parse(text = paste(colname," == 1",sep="")))
  false_condition <- eval(parse(text = paste(colname," == 0",sep="")))
  
  true_df <- train_df[true_condition,]
  false_df <- train_df[false_condition,]
  
  sample_size <- fold_size/2
  
  if (nrow(true_df) < sample_size) {
    sample_size <- fold_size - nrow(true_df)
  } else {
    sample_size <- fold_size/2
    true_df <- true_df[sample(nrow(true_df),sample_size,replace=FALSE),]
  }
  
  false_df <- false_df[sample(nrow(false_df),sample_size,replace=FALSE),]
    
  new_df <- unique(rbind(true_df,false_df))

  form <- NA
  
  #if (length(unique(true_df$SITUATION)) == length(situations)) {
  #  train_on_situation <- TRUE
  #}

  if (train_on_situation) {
    form <- gsub(" ","",paste(type_new," ~ SITUATION + LOCATION.FOUND.LATITUDE + LOCATION.FOUND.LONGITUDE + LOCATION.FOUND.ELEVATION + NUMBER.OF.RANGERS.INVOLVED"));
  } else {
    form <- gsub(" ","",paste(type_new," ~ LOCATION.FOUND.LATITUDE + LOCATION.FOUND.LONGITUDE + LOCATION.FOUND.ELEVATION + NUMBER.OF.RANGERS.INVOLVED"));
  }
  
  suppressWarnings({
    new_df$LOCATION.FOUND.LATITUDE <- new_df$LOCATION.FOUND.LATITUDE + rnorm(50)
    new_df$LOCATION.FOUND.LONGITUDE <- new_df$LOCATION.FOUND.LONGITUDE + rnorm(50)
    new_df$LOCATION.FOUND.ELEVATION <- new_df$LOCATION.FOUND.ELEVATION + rnorm(50)
    new_df$NUMBER.OF.RANGERS.INVOLVED <- new_df$NUMBER.OF.RANGERS.INVOLVED + rnorm(50)
  })
  
  
  
  
  
  cat(paste("\nNROW: ",nrow(new_df),"TRUE:",nrow(true_df),"FALSE:",nrow(false_df),"\n"))
  cat(sprintf("%-50s\t", type),paste(get_acc(new_df,form,type),"%"),"\n")
}

```

```{r}

```

```{r}

```

```{r}
```
